# Generated by Django 4.1.3 on 2022-11-22 10:19

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20220208_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.FileField(upload_to=post.models.user_directory_path, verbose_name='Picture'),
        ),
    ]
