# Generated by Django 4.1.3 on 2022-11-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_post_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='status',
            field=models.SmallIntegerField(null=True),
        ),
    ]
