# Generated by Django 4.1.3 on 2022-11-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_alter_notification_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='archive',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
